#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the isBalanced function below.
def isBalanced(s):
 stack = []
 for c in s :
     if( c in '{[(' ):
         stack.append(c)
     else:
         if(len(stack) <= 0):
             return "NO"
         current_char = stack.pop()
         if((current_char== "(" and  c == ")") or (current_char== "{" and  c == "}") or(current_char== "[" and  c == "]")  ):
             continue;
         else:
             return "NO"
 if(len(stack) >0):
    return "NO" 
 else:
    return "YES"   

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        s = input()

        result = isBalanced(s)

        fptr.write(result + '\n')

    fptr.close()
