#!/bin/python3

import os
import sys

#
# Complete the equalStacks function below.
#
def equalStacks(h1, h2, h3):
    #
    # Write your code here.
    #
    first = set()
    second = set()
    third = set()

    sum = 0
    for i in range(len(h1), 0, -1):
        sum += h1[i-1]
        first.add(sum)
    sum = 0
    for i in range(len(h2), 0, -1):
        sum += h2[i-1]
        if sum in first:
            second.add(sum)
    
    sum = 0
    for i in range(len(h3), 0, -1):
        sum += h3[i-1]
        if sum in second:
            third.add(sum)
    # print(max(third))
    if(len(third) == 0):
        return 0
    else:
        return max(third)


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n1N2N3 = input().split()

    n1 = int(n1N2N3[0])

    n2 = int(n1N2N3[1])

    n3 = int(n1N2N3[2])

    h1 = list(map(int, input().rstrip().split()))

    h2 = list(map(int, input().rstrip().split()))

    h3 = list(map(int, input().rstrip().split()))

    result = equalStacks(h1, h2, h3)

    fptr.write(str(result))

    fptr.close()
